name: Build and run data processing pipeline

# Triggers the workflow on push of a new tag to origin.
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context
        run:   echo "$GITHUB_CONTEXT"
        shell: bash
        env:
         GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Write .env file
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          touch .env
          echo RAW_DATA_PATH=https://github.com/$GITHUB_REPOSITORY/archive/ >> .env
          echo DATA_BUCKET={{ secrets.DATA_BUCKET }} >> .env
          echo AWS_ACCESS_ID={{ secrets.AWS_ACCESS_ID }} >> .env
          echo AWS_SECRET_KEY={{ secrets.AWS_SECRET_KEY }} >> .env
          echo MAPBOX_USERNAME={{ secrets.MAPBOX_USERNAME }} >> .env
          echo MAPBOX_TOKEN={{ secrets.MAPBOX_TOKEN }} >> .env
          echo DATA_VERSION=$RELEASE_VERSION >> .env
          echo DEPLOY=1 >> .env
          echo CLEAN=1 >> .env
          echo BUILD_GEOJSON=0 >> .env
          echo BUILD_TYPES={{ secrets.BUILD_TYPES }} >> .env
          echo BUILD_METRO_LIST=1 >> .env
          echo BAR_CHARTS=1 >> .env
          UPLOAD_MAPBOX_SHAPES=1 >> .env
          UPLOAD_MAPBOX_POINTS=1 >> .env
          echo DEBUG=1 >> .env
          cat .env
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build . --pull --no-cache -t hyperobjekt/ddk-etl
      - name: Run docker image
        run: docker run --env-file .env hyperobjekt/ddk-etl
